name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: '2.6'
            gemfile: 'rails5.gemfile'
          - ruby-version: '2.7'
            gemfile: 'rails6.gemfile'
          - ruby-version: '3.0'
            gemfile: 'Gemfile'

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rspec
